
package GUI;


public class GetData extends javax.swing.JFrame {
 
    public GetData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Enunciado = new javax.swing.JLabel();
        RutasEmpresa = new javax.swing.JTextField();
        PedidosRealizar = new javax.swing.JTextField();
        CamionesEnCadaRuta = new javax.swing.JTextField();
        CamionesPorRuta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Siguiente = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingresar Datos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);
        setLocation(new java.awt.Point(200, 200));
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(600, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        Enunciado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Enunciado.setText("Antes de iniciar, ingrese los siguientes datos:");
        getContentPane().add(Enunciado);
        Enunciado.setBounds(20, 180, 440, 22);

        RutasEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RutasEmpresaActionPerformed(evt);
            }
        });
        getContentPane().add(RutasEmpresa);
        RutasEmpresa.setBounds(330, 250, 220, 30);

        PedidosRealizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PedidosRealizarActionPerformed(evt);
            }
        });
        getContentPane().add(PedidosRealizar);
        PedidosRealizar.setBounds(330, 350, 220, 30);

        CamionesEnCadaRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CamionesEnCadaRutaActionPerformed(evt);
            }
        });
        getContentPane().add(CamionesEnCadaRuta);
        CamionesEnCadaRuta.setBounds(330, 400, 220, 30);

        CamionesPorRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CamionesPorRutaActionPerformed(evt);
            }
        });
        getContentPane().add(CamionesPorRuta);
        CamionesPorRuta.setBounds(330, 300, 220, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel2.setText("Cantidad de pedidos a realizar:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 350, 330, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel7.setText("Cantidad de camiones por cada ruta:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 400, 330, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel8.setText("Cantidad de camiones por ruta:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(70, 300, 330, 20);

        Siguiente.setBackground(new java.awt.Color(255, 204, 0));
        Siguiente.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        Siguiente.setForeground(new java.awt.Color(255, 255, 255));
        Siguiente.setText("SIGUIENTE");
        Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(Siguiente);
        Siguiente.setBounds(230, 470, 140, 40);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dust Road Co..png"))); // NOI18N
        getContentPane().add(Logo);
        Logo.setBounds(150, -20, 450, 200);

        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel5.setText("Cantidad de rutas de la empresa:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 250, 330, 20);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/WhiteBackground.jpg"))); // NOI18N
        Background.setText("jLabel7");
        getContentPane().add(Background);
        Background.setBounds(-10, -10, 620, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RutasEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RutasEmpresaActionPerformed
       
    }//GEN-LAST:event_RutasEmpresaActionPerformed

    private void SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteActionPerformed
    
         
            
    }//GEN-LAST:event_SiguienteActionPerformed

    private void PedidosRealizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PedidosRealizarActionPerformed
       
    }//GEN-LAST:event_PedidosRealizarActionPerformed

    private void CamionesEnCadaRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CamionesEnCadaRutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CamionesEnCadaRutaActionPerformed

    private void CamionesPorRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CamionesPorRutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CamionesPorRutaActionPerformed
    

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GetData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GetData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GetData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GetData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GetData().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JTextField CamionesEnCadaRuta;
    private javax.swing.JTextField CamionesPorRuta;
    private javax.swing.JLabel Enunciado;
    private javax.swing.JLabel Logo;
    private javax.swing.JTextField PedidosRealizar;
    private javax.swing.JTextField RutasEmpresa;
    private javax.swing.JButton Siguiente;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables

   
}
